docker image scantest

diff --git a/.github/workflows/scan_dockerimage.yml b/.github/workflows/scan_dockerimage.yml
--- a/.github/workflows/scan_dockerimage.yml
+++ b/.github/workflows/scan_dockerimage.yml
@@ -28,49 +28,47 @@ jobs:
           cd build
           docker build -t test/virus-image .
           docker image ls
-          sudo tree $SCAN_DIR /f
-          # sudo ls $SCAN_DIR
 
-      # - name: scan clamav
-      #   id: scan_clamav
-      #   run: |
-      #     scandir=$(pwd)/${{ github.event.inputs.scandir }}
+      - name: scan clamav
+        id: scan_clamav
+        run: |
+          scandir=$(pwd)/${{ github.event.inputs.scandir }}
 
-      #     echo "# Virus Report" > /tmp/report.log
-      #     echo "## ScanDir" >> /tmp/report.log
-      #     echo "- ${scandir}" >> /tmp/report.log
-      #     echo "## ScanResult" >> /tmp/report.log
+          echo "# Virus Report" > /tmp/report.log
+          echo "## ScanDir" >> /tmp/report.log
+          echo "- ${scandir}" >> /tmp/report.log
+          echo "## ScanResult" >> /tmp/report.log
 
-      #     docker run \
-      #       --rm \
-      #       --mount type=bind,source=$scandir,target=/scandir \
-      #       --mount type=bind,source=/tmp,target=/tmp \
-      #       clamav/clamav:0.105 \
-      #       freshclam --on-update-execute="clamscan -r -l /tmp/result.log /scandir"
+          sudo docker run \
+            --rm \
+            --mount type=bind,source=$scandir,target=/scandir \
+            --mount type=bind,source=/tmp,target=/tmp \
+            clamav/clamav:0.105 \
+            freshclam --on-update-execute="clamscan -r -l /tmp/result.log /scandir"
 
-      # - name: check result
-      #   id: check_result
-      #   run: |
-      #       echo "[scan result]"
-      #       cat /tmp/result.log
+      - name: check result
+        id: check_result
+        run: |
+            echo "[scan result]"
+            cat /tmp/result.log
 
-      #       failed_check=$(cat /tmp/result.log | grep FOUND | wc -m | awk '{print $1}')
+            failed_check=$(cat /tmp/result.log | grep FOUND | wc -m | awk '{print $1}')
 
-      #       # FOUNDが1件でもあったらjobを失敗させる
-      #       if [ ${failed_check} -ne 0 ]; then
-      #         echo "*****************************"
-      #         echo "[Failed] virus is existed !!!"
-      #         echo "*****************************"
-      #         exit 1
-      #       fi 
+            # FOUNDが1件でもあったらjobを失敗させる
+            if [ ${failed_check} -ne 0 ]; then
+              echo "*****************************"
+              echo "[Failed] virus is existed !!!"
+              echo "*****************************"
+              exit 1
+            fi 
 
-      # - name: Create issue
-      #   if: failure() && steps.check_result.outcome == 'failure'
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   run: |
-      #     cat /tmp/result.log >> /tmp/report.log
-      #     gh issue create \
-      #     --title "[Failed] virus is existed !!!" \
-      #     --label virus \
-      #     --body-file /tmp/report.log
+      - name: Create issue
+        if: failure() && steps.check_result.outcome == 'failure'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          cat /tmp/result.log >> /tmp/report.log
+          gh issue create \
+          --title "[Failed] virus is existed !!!" \
+          --label virus \
+          --body-file /tmp/report.log
