clamav install test22 - test virus

diff --git a/.github/workflows/scan.yml b/.github/workflows/scan.yml
--- a/.github/workflows/scan.yml
+++ b/.github/workflows/scan.yml
@@ -40,7 +40,8 @@ jobs:
 
             # FOUNDが1件でもあったらjobを失敗させる
             if [ ${failed_check} -ne 0 ]; then
-              return 1
+              echo "!!!Failed virus check!!!"
+              exit 1
             fi 
 
       - name: Create issue
